### ISSUE TITLE
Selection time frame

### ISSUE THREAD

**Issue by spotto** [CoVaRR-NET/duotang#103]
Hi all - We should make the time frame of all the selection graphs and the plot of s estimates focused on current trends.  My suggestion would be to have a four-month cut-off for the data (i.e., include only data within four months of the most recent data), so this updates automatically with each update.  Thanks, Sally

**Comment by RaphaelRaphael** [comment]
time frame is updated : 
as.Date(VirusSeq_release)-days(120)
