### ISSUE TITLE
Disentangling selection on different sites

### ISSUE THREAD

**Issue by spotto** [CoVaRR-NET/duotang#104]
We've discussed the challenges estimating selection on specific mutations vs changes due to linkage disequilibrium with sites that are actually under selection.

An useful analysis would be to estimate changes in the frequency of mutations in different lineages (e.g., as shown in the new "Mutations over time" graph in covspectrum (https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=BA.2.75*&). 

A sign test would be a good start:  in how many independent lineages does a particular mutation show positive vs negative frequency change over time?  But I could also see value in a plot giving estimates and CI for selection from the frequency rise over time (like our current "Fastest growing lineages" plot but by mutation with each dot representing that mutations' growth in a different lineage).

Now that covspectrum provides the frequency change within lineages, it would be much easier, because we could just use that as input data.

**Comment by bfjia** [comment]
@anwarMZ Issue in covid mvp
