### ISSUE TITLE
Overestimating clock rate for BA.2, clade needs to be split

### ISSUE THREAD

**Issue by ArtPoon** [CoVaRR-NET/duotang#107]
This is from our current root-to-tip plot:
<img width="279" alt="Screen Shot 2022-12-06 at 12 25 20 PM" src="https://user-images.githubusercontent.com/1109328/205980292-b5c683e4-829e-41ed-bda7-b32584070577.png">

Note red corresponds to BA.2 and derived lineages.  There are two clusters (the upper-right cluster is obscured by other points) that is causing the root-to-tip regression to estimate a higher rate of evolution than should be supported by the data.
This upper cluster appears to be associated with BA.2.75 and derived lineages.  I am going to see what happens if I separate this from the rest of BA.2.

**Comment by ArtPoon** [comment]
![image](https://user-images.githubusercontent.com/1109328/205985308-3d343657-47f3-4a13-80ae-68caba2c8bea.png)

Adding BA.2.75 as a `pango.group` seems to resolve the problem.

**Comment by ArtPoon** [comment]
Going to push to new branch `iss107` and issue pull request.  Cleaning up code in `scanlineages.R` right now

**Comment by fionabrinkman** [comment]
Thanks for this! Great idea!

**Comment by fionabrinkman** [comment]
What are the remaining red on the top then? Would be good to look at this further.

**Comment by RaphaelRaphael** [comment]
Thanks Art it s BA.2.75, I will separate this group and make it orange !

**Comment by RaphaelRaphael** [comment]
![image](https://user-images.githubusercontent.com/3922571/206037323-fa4ad709-2b3b-4542-a28b-fd6a1ae79eab.png)
