### ISSUE TITLE
have a global color pallette to harmonize colors across all graphs

### ISSUE THREAD

**Issue by bfjia** [CoVaRR-NET/duotang#111]
- possible predefined set colors for lineages of interest and then randomly generate the colors for the other lineages.
- possible: use same color spectrum for all subsublineages of sublineages?

**Comment by bfjia** [comment]
VOCVOI has pre-defined colors already for lineages of interest

**Comment by bfjia** [comment]
agreed. Should the VOCVOI colors be used everywhere then?

**Comment by RaphaelRaphael** [comment]
yes ! And now it s the cae so we could close this one ?

**Comment by ArtPoon** [comment]
Ideally, we would wait until the VOCVOI palette is indeed used for all plots

**Comment by RaphaelRaphael** [comment]
I think it is the case now that the trees have it

**Comment by ArtPoon** [comment]
in that case sounds like it's ok to close, thanks
