### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by ArtPoon** [CoVaRR-NET/duotang#112]
* bioconductor
* ggfree

**Comment by bfjia** [comment]
There's a conda environment yaml file on the repo too as a possible alternative.

**Comment by ArtPoon** [comment]
We should not have to require users to use conda

**Comment by ArtPoon** [comment]
Going through the R packages and removing those that are not being used, or scarcely used.

**Comment by ArtPoon** [comment]
See branch `iss113`
