### ISSUE TITLE
case count in Omicron sublineages

### ISSUE THREAD

**Issue by RaphaelRaphael** [CoVaRR-NET/duotang#121]
The case count y-scale on the rigth of some Omicron sublineages in Canada is not well set

[Slack Message](https://covarr-net.slack.com/archives/C046T5JA48H/p1672776316965959)

**Comment by bfjia** [comment]
Could you elaborate further on this? I'm not quite getting what you mean. thanks!

**Comment by RaphaelRaphael** [comment]
This is an example of a problematic graph 

![image](https://user-images.githubusercontent.com/3922571/212149617-b17a52b0-73da-40d4-b735-27991c582a1e.png)
