### ISSUE TITLE
Y-axis scaling of case count data

### ISSUE THREAD

**Issue by bfjia** [CoVaRR-NET/duotang#136]
The current scaling (max value + 10% of max) makes the plot looks more wavy than it should. Perhaps we can explore changing it to the same scaling across all provinces and then transform it into case/100000population.

**Comment by spotto** [comment]
I downloaded the [data from Stats Can by province](https://www150.statcan.gc.ca/t1/tbl1/en/cv.action?pid=1710000501) and inserted a row for the number of 70+ individuals by province in 2022 (row 12 in this csv file.)

[1710000501-eng.csv](https://github.com/CoVaRR-NET/duotang/files/10680292/1710000501-eng.csv)

That can be used to estimate the number of cases in 70+ per individual, so we can use a common y-axis limit.
