### ISSUE TITLE
Errors when running download.sh on macOS

### ISSUE THREAD

**Issue by ArtPoon** [CoVaRR-NET/duotang#137]
* line: `datestamp=$(date --utc +%Y-%m-%dT%H_%M_%S)`
* error:
```
date: illegal option -- -
usage: date [-jnRu] [-r seconds|file] [-v[+|-]val[ymwdHMS]]
            [-I[date | hours | minutes | seconds]]
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
```
* remedy: use `date -u "+%Y-%m-%dT%H_%M_%S"` if macOS

**Comment by ArtPoon** [comment]
Not sure what to do about this one:
```
Data source is VirusSeq
--2023-02-09 17:46:03--  https://singularity.virusseq-dataportal.ca/download/archive/all
Resolving singularity.virusseq-dataportal.ca (singularity.virusseq-dataportal.ca)... 142.1.177.211, 142.1.177.201, 142.1.177.205
Connecting to singularity.virusseq-dataportal.ca (singularity.virusseq-dataportal.ca)|142.1.177.211|:443... failed: Network is unreachable.
Connecting to singularity.virusseq-dataportal.ca (singularity.virusseq-dataportal.ca)|142.1.177.201|:443... failed: Network is unreachable.
Connecting to singularity.virusseq-dataportal.ca (singularity.virusseq-dataportal.ca)|142.1.177.205|:443... failed: Network is unreachable.
gtar: This does not look like a tar archive
gzip: (stdin): unexpected end of file
gtar: Child returned status 1
gtar: Error is not recoverable: exiting now
gtar: This does not look like a tar archive
gzip: (stdin): unexpected end of file
gtar: Child returned status 1
gtar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "/Users/art/git/duotang/scripts/pango2vseq.py", line 37, in <module>
    fieldnames = list(rows[0].keys())
IndexError: list index out of range
```

**Comment by bfjia** [comment]
i changed the update process and did not consider macOS
use ViralAI as the datasource. It's much faster.

**Comment by bfjia** [comment]
also the 2nd error is probably because virusseq is down atm. So the connection failed resulting in an empty output file

**Comment by bfjia** [comment]
as an alternative workaround: run the update.sh script in root and just specify the date argument. `./update.sh --noconda --date YYYY-MM-DD` 
Then kill the script when you see "separating out the recombinants from the data..." from the console. This would give you the data download.

**Comment by bfjia** [comment]
The download.sh script is now part of the update.sh script and will be deprecated once some more testing is done.

you can simulate the old download.sh script via 
`./update.sh --downloadonly --noconda  --skipgsd --date $(date -u "+%Y-%m-%d")`
