### ISSUE TITLE
Weigh y-axis of selection graphs

### ISSUE THREAD

**Issue by suskraem** [CoVaRR-NET/duotang#15]
Sally: I recommend instead that we weight by population size in each province.  For example, say that BC were 25% of Canada and QC were 75% of Canada, and that we had X and Y data points on a given day from the two, of which pX and pY are BA.2. Then for each circle, the size of the data point would continue to be X*pX+Y*pY (total amount of BA.2 data), but the y-axis would be set to 0.25*pX+0.75*pY, rather than the current (X*pX+Y*pY)/(X+Y).  Similarly, for the confidence intervals, we would use 0.25*lowercurve3[BC]+0.75*lowercurve3[QC] to get the weighted average for the lower bound for BA.2. I wasn’t sure how to best do this because the averaging for Canada would require output across all of the provinces (the lowercurve2, uppercurve2, lowercurve3, uppercurve3), which are not currently in the main package.

**Comment by bfjia** [comment]
need to get population size for each province to compute. Should be straight forward for some graphs. Need more investigation
