### ISSUE TITLE
Table of contents is not useful

### ISSUE THREAD

**Issue by ArtPoon** [CoVaRR-NET/duotang#157]
Currently it is displaying the least useful parts of the notebook, *e.g.*, "Future work", and hiding the most useful parts, *e.g.*, "Fastest growing lineages in Canada".  I am proposing the following fixes:
* Demote Future Development, Methodology, Data notes by province, List of useful tools, Acknowledgements and sources, and Session info into levels under **Appendix**
* Promote all sections under "SARS-CoV-2 in Canada" to upper levels - remove "SARS-CoV-2 in Canada" as a heading, it should be obvious that this is the topic

**Comment by bfjia** [comment]
Further changes to the TOC:

- Promote SARS-COV2 in canada and Selection on Omicron headings. 
- Selection on omicron isntead of selection trends by variant.
- fastest growling lineages > remove canada.
- 
- SARS-COV2-2 in canada > introduction and limitations. 
- Pango lineage table > remove description
- Variants over time. > rm description
- 
- BA.* sublineages > rm selection. 
-
