### ISSUE TITLE
duplicate GISAID id in VirusSeq

### ISSUE THREAD

**Issue by RaphaelRaphael** [CoVaRR-NET/duotang#16]
So the way I extract metadata in bash

filefromVirusSeq=9c65ea71-30bb-49b1-bb60-85dbc31173b3
tar -axf source/$filefromVirusSeq -O  files-archive-$filefromVirusSeq.tsv | tr ' ' '_'  | sed 's/\t\t/\tNA\t/g' | sed 's/\t\t/\tNA\t/g' | sed 's/\t$/\tNA/g'> datafromvirrusseq_$shortname

From here column 44 have 36 duplicates like this one : EPI_ISL_2479805

**Comment by bfjia** [comment]
@anwarMZ

**Comment by bfjia** [comment]
Extension of Issue #42

**Comment by bfjia** [comment]
@anwarMZ can this issue be closed now?

**Comment by RaphaelRaphael** [comment]
Before closing it, I would like to know how to interpret the output of the download script `virusseq.gisaid_duplicate_ids.txt` could it be more explicit and can it be documented in CONTRINUTING.md ?
