### ISSUE TITLE
Plot of fastest growing mutations

### ISSUE THREAD

**Issue by fionabrinkman** [CoVaRR-NET/duotang#164]
Plot of fastest growing mutations (selection estimates and their 95% confidence intervals, like the fastest growing lineages plot) - starting with those mutations both (1) observed and (2) noted for immune evasion via the Bloom lab tools (such as https://jbloomlab.github.io/SARS2_RBD_Ab_escape_maps/escape-calc/ etc set for eliciting virus including BA.5 and and neutralizing XBB).

Sticking this in here quickly, as I can't attend the next meeting so just want to flag it, with apologies if this is already an issue (as this has been discussed).

**Comment by bfjia** [comment]
We might not have enough data for Canada only, This could be a COVID-MVP issue @anwarMZ
