### ISSUE TITLE
Could we have an XBB diversity tree? 

### ISSUE THREAD

**Issue by fionabrinkman** [CoVaRR-NET/duotang#176]
An XBB diversity tree would be really helpful right now. Right now we just have an XBB time tree and no way to see the diversity for this important phyletic group, since XBB isn't in the other diversity trees.

**Comment by RaphaelRaphael** [comment]
If we code the 2 different branch lengths in the tree file, could we have a way to toggle between diversity and time tree (Just dynamically changing the branch lengths and scale)

**Comment by ArtPoon** [comment]
That's what I'm thinking.  We are passing trees from R to JS as two data frames: one for nodes and one for edges.  Adding columns to those data frames is no big deal.

**Comment by RaphaelRaphael** [comment]
So coding 2 distances in the newick tree is not hard, I could do a script merging 2 trees into one with both distances recoded as dist1|dist2

**Comment by bfjia** [comment]
Agreed with both of the comments. Part of my planned package size reduction was going to merge the separate tabbed trees together into 1 json file and let JS handle the data switching. These suggestions goes well with that.

I prefer Art's approach of extracting all the length from separate trees into the same Json. That way we don't have to modify the current update process either.
