### ISSUE TITLE
Unchecking all boxes in RTT plot results in all points being located to the top left corner when checking boxes afterwards.

### ISSUE THREAD

**Issue by bfjia** [CoVaRR-NET/duotang#178]
If you uncheck all checkboxes on the RTT plot, then re-check any checkboxes, all points gets plotted to the top left corner. 

![image](https://user-images.githubusercontent.com/6340682/229605669-fbee45e1-1aa0-4dcb-a968-f656ff372281.png)

**Comment by ArtPoon** [comment]
Ha, that's a fun edge case.

**Comment by bfjia** [comment]
Resolved in PR #268
