### ISSUE TITLE
wording update

### ISSUE THREAD

**Issue by spotto** [CoVaRR-NET/duotang#193]
very small duotang issue:  change “Thick point border indicates a lineage have a positive selection in multiple provinces” to “Thick point border indicates a lineage with a positive selection coefficient in multiple provinces”

[Slack Message](https://covarr-net.slack.com/archives/C025AGXG7JT/p1682443398726079)

**Comment by fionabrinkman** [comment]
Just seeing this now! Note I just added an issue suggesting we update the figure legend as well to clarify what the different dots are. See issue #198.
