### ISSUE TITLE
Update legend to clarify the Fastest Growing Lineages in Canada different dots?

### ISSUE THREAD

**Issue by fionabrinkman** [CoVaRR-NET/duotang#198]
It just dawned on me that, though, the excellent Fastest Growing Lineages in Canada plot clearly states the point of the thicker line around those points reflecting lineages growing in multiple provinces in Canada, this really needs to be noted in the legend for the Canada plot for clarity. Welcome thoughts on the best way to do this, but perhaps just have two rows for each dot type indicating that the larger one is "Positive selection in multiple Provinces" and the other is "Positive selection only one province to date"? Happy to discuss!

**Comment by bfjia** [comment]
Thick border indicates multiple provinces In the title instead of part of the plot.
