### ISSUE TITLE
Minor fix to text under "List of Useful Tools"

### ISSUE THREAD

**Issue by fionabrinkman** [CoVaRR-NET/duotang#200]
Minor grammar fix just noticed (and might as well clarify that its a subset of tools of course!):

Change under List of Useful Tools from:
"Collect a list of bioinformatics, phylogenetic, and modelling tools that are useful for SARS-CoV-2 analyses"
to:
"A selection of bioinformatics, phylogenetic, and modelling tools that are useful for SARS-CoV-2 analyses"

Sorry this wasn't noticed until now!

**Comment by bfjia** [comment]
Resolved with PR #199
