### ISSUE TITLE
Mention CoVaRR-Net!

### ISSUE THREAD

**Issue by fionabrinkman** [CoVaRR-NET/duotang#218]
I just noticed, we don't EVER mention CoVaRR-Net on the Duotang. Oops! 

I suggest we change the text that says "Pillar 6 - CAMEO" to 

"Pillar 6 - CAMEO (Computational Analysis, Modelling and Evolutionary Outcomes Group), CoVaRR-Net (Coronavirus Variants Rapid Response Network)"

And acknowledge CoVaRR-Net at the bottom.

**Comment by bfjia** [comment]
ngl, putting that all into the author fields makes it really long and kind of overwhelming as a subtitle. I propose we change the author to "Pillar 6 - CAMEO, CoVaRR-Net" and mention the full names and acronyms in the introduction: 

## Introduction
This notebook is built to explore Canadian SARS-CoV-2 genomic and epidemiological data with the aim of investigating viral evolution and spread. It is for discussion within the Coronavirus Variants Rapid Response Network (CoVaRR-Net)'s pillar 6 - CAMEO (Computational Analysis, Modelling and Evolutionary Outcomes Group) team and for sharing with collaborators, e.g. public health labs.
.....

CoVaRR-Net will be put into the acknowledgements.
