### ISSUE TITLE
Substitution rate error

### ISSUE THREAD

**Issue by spotto** [CoVaRR-NET/duotang#257]
Github issue:  There is something wrong with the scale of duotang’s “Molecular clock estimates”, which suggests ~1500 substitutions per genome per day.  That’s way too high.  It should be closer to 0.06 substitutions per genome per day (about one change every two weeks).  Did this accidentally get multiplied by the genome size?  <@U02NQPKG3UJ> <@U03VC9B7PC3>

[Slack Message](https://covarr-net.slack.com/archives/C020WAJS0DD/p1692715538489999?thread_ts=1692714535.735499&cid=C020WAJS0DD)

**Comment by ArtPoon** [comment]
Ok I'll check it out

**Comment by ArtPoon** [comment]
I suspect the problem is that when I replaced the RTT plot with an interactive JS widget, the code for calculating clock rates did not get updated.   It is probably pulling raw DOM coordinates instead of the divergence (y-axis) values.

**Comment by ArtPoon** [comment]
Ok this was a pretty easy fix.  @spotto 's intuition was correct - for some reason rescaling the rate estimates by genome length became superfluous, so I am removing this from the `dev` branch:
```diff
diff --git a/scripts/fit-rtt.R b/scripts/fit-rtt.R
index a5e539f5..ec012382 100644
--- a/scripts/fit-rtt.R
+++ b/scripts/fit-rtt.R
@@ -80,9 +80,9 @@ get.ci <- function(fits) {
   ci <- lapply(fits, confint.rlm)
   est <- data.frame(
     n = sapply(fits, function(f) nrow(f$x)),                            
-    est = 29903*sapply(fits, function(f) f$coef[2]),
-    lower.95 = 29903*sapply(ci, function(f) f[2,1]),
-    upper.95 = 29903*sapply(ci, function(f) f[2,2])
+    est = sapply(fits, function(f) f$coef[2]),
+    lower.95 = sapply(ci, function(f) f[2,1]),
+    upper.95 = sapply(ci, function(f) f[2,2])
   )
   est$Lineage <- row.names(est)
   est
```

**Comment by bfjia** [comment]
Thank you Art
