### ISSUE TITLE
# named variants in circulation in Canada

### ISSUE THREAD

**Issue by spotto** [CoVaRR-NET/duotang#269]
Hi Justin - Since I keep wanting to know, could we add to duotang the number of named lineages over the time span of the report?  [Only if easy.]

[Slack Message](https://covarr-net.slack.com/archives/D04JYBEPJB0/p1694091297241529)

**Comment by bfjia** [comment]
@spotto Could you please clarify "time spam of the report", do you mean since inception or the last 120 days?
