### ISSUE TITLE
Problems calculating Hessian for confidence intervals

### ISSUE THREAD

**Issue by ArtPoon** [CoVaRR-NET/duotang#275]
* to calculate confidence intervals on fitting logistic growth models to variant frequencies over time, we are using the `mle2` optimization method 
* `mle2` calculates the [Hessian matrix](https://en.wikipedia.org/wiki/Hessian_matrix) to estimate the confidence interval associated with the maximum likelihood parameter estimates
* this fails in some cases, *e.g.*, where the estimated frequencies are close to zero

**Comment by bfjia** [comment]
This issue had been resolved by using a sliding window of date ranges, in increments of 10, until we find a point where we re able to estimate confidence intervals.
