### ISSUE TITLE
Color accessibility for lineage palette

### ISSUE THREAD

**Issue by ArtPoon** [CoVaRR-NET/duotang#29]
* Need to check palette for color accessibility
* Using similar colors for BA.1 and BA.2 is problematic

**Comment by bfjia** [comment]
manually define sets of color palettes for that are important to distinct between closely related colors. Otherwise let R handle the color picking.
e.g. the BA2, BA3, BA5 should have distinct colors whereas it's less important for Alpha, Delta to have distinct colors
