### ISSUE TITLE
Epidemiological data sourcing

### ISSUE THREAD

**Issue by ArtPoon** [CoVaRR-NET/duotang#30]
May need to switch data source for longitudinal case count data; some sources were suggested:
https://github.com/mountainMath/CanCovidData

**Comment by bfjia** [comment]
@ArtPoon Can you elaborate/remind us of the context surrounding this issue?

**Comment by ArtPoon** [comment]
The issue was that our source for case counts in Canada was being discontinued.  This is no longer a relevant issue because the streamgraph does not display case count data.
