### ISSUE TITLE
High BA.2 mutation rate

### ISSUE THREAD

**Issue by spotto** [CoVaRR-NET/duotang#341]
Just moving this to GitHub (low priority): Consider adding to “Molecular clock estimates (based on three independent subsamples)” at the very end: “BA.2. appears to have a higher rate of mutation (red) because it includes highly divergent sub-groups (i.e., potential saltation lineages), including CM.*”

[Slack Message](https://covarr-net.slack.com/archives/D04JYBEPJB0/p1712970713846339)

**Comment by bfjia** [comment]
Resolved as of the last update #340
