### ISSUE TITLE
speeding up the webpage

### ISSUE THREAD

**Issue by bfjia** [CoVaRR-NET/duotang#343]
- Downsample the tree further to reduce data being transmitted.
- Reduce the frequency plots to be static. NOT the last 120 days.

**Comment by ArtPoon** [comment]
Most of the memory used by the page are taken up by SVG elements (the trees and the interactive RTT plot):
![image](https://github.com/CoVaRR-NET/duotang/assets/1109328/5fa42076-9140-46b4-9f2f-5f6ff3713874)

**Comment by bfjia** [comment]
Resolved with PR #345
