### ISSUE TITLE
Loss of the Health InfoBase case counts

### ISSUE THREAD

**Issue by bfjia** [CoVaRR-NET/duotang#361]
I spent some time looking at sources of provincial COVID-19 case counts today given the recent news about the InfoBase, and it's not looking great. I welcome suggestions and links if you know there's another source of this information. 

Provinces with data still available*:

- Quebec source remained the same, still reporting daily case counts, and available through INSPQ: https://www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv
- The Alberta reports weekly case counts via their provincial dashboard https://www.alberta.ca/stats/dashboard/respiratory-virus-dashboard.htm?data=summary#summary. I didn't see any data available for download, but the COVID-19 weekly case plot on their website is javascript based so the data is scrapable. Thus, we can still pull Alberta data with some well crafted page scraping.  
- New Brunswick has a monthly report released as a PDF document. https://www2.gnb.ca/content/gnb/en/corporate/promo/respiratory-watch.html. This document does not contain historical data (other than static plots) and contains only the number of cases for the reporting week. It will be almost impossible to parse via machine but at least the case counts can be manually entered for Duotang. 
- 

Provinces that's no longer available:

- Ontario, unfortunately, had decided to pause their reporting to the Ontario Respiratory Virus Tool as of June 14th. I don't see any alternatives to this. This means that we will lose the case count for Ontario. https://www.publichealthontario.ca/en/Data-and-Analysis/Infectious-Disease/Respiratory-Virus-Tool
- BC/SK/MB/NS/NL hasn't reported case data from a provincial source for a while now, and I don't see any indication that there's an alternative source other than the Health InfoBase. 
- 

For reference, we currently have data for BC/AB/ON/QC/NS/NB/NL using the Health InfoBase CSV. 

Should we lose the Health InfoBase CSV, we will only have consistent data from Quebec, Alberta is OK and manageable, and New Brunswick with a 1 month delay.

**Comment by bfjia** [comment]
Potentially could consider using outbreak numbers that is still available via the Health-infobase to track overall Canadian trends. The correlation between outbreak numbers and case numbers is very high. 
![image](https://github.com/CoVaRR-NET/duotang/assets/6340682/ebcb5d86-547b-4630-b35e-32feaf1c375b)

**Comment by bfjia** [comment]
- Cases by age and gender CSV still report cases/hospitalization for the week of Jun 8th. https://health-infobase.canada.ca/src/data/covidLive/covid19-epiSummary-ageGender.csv
-- This data, however is under reported as it excludes values that does not have gender/age information
- BC Cases: https://bccdc.shinyapps.io/respiratory_covid_sitrep/
-- Case counts can be extracted using the SVG line elements. 

- Will outbreak definition be consistent?

- For the correlation plots, highlight the last month.

**Comment by bfjia** [comment]
![image](https://github.com/CoVaRR-NET/duotang/assets/6340682/03bf744d-045f-4e21-8a0e-f62637abee2a)

Outbreak/Cases plot with last 4 data points highlighted in red

**Comment by bfjia** [comment]
Another source of data could be the case positivity rate from the respiratory virus reports. https://www.canada.ca/en/public-health/services/surveillance/respiratory-virus-detections-canada/2023-2024/week-23-ending-june-8-2024.html

**Comment by bfjia** [comment]
Sally: Could you take a look to see which has been most correlated with reported case numbers (and each other): outbreaks, test positivity, or test positivity*test number

**Comment by bfjia** [comment]
![CaseCount_vs_Positive_Count](https://github.com/CoVaRR-NET/duotang/assets/6340682/fca32f4f-1f1c-4d5a-bfa1-81a44df7224c)
![CaseCount_vs_Positive_Rate](https://github.com/CoVaRR-NET/duotang/assets/6340682/55df1ec6-4f3d-4663-9ec0-21ee3a9b3446)
![CaseCount_vs_Gender_Cases_Count](https://github.com/CoVaRR-NET/duotang/assets/6340682/cad7f8f6-1ea8-4354-a4b1-34ebd22e6c00)
![CaseCount_vs_Outbreaks_Count](https://github.com/CoVaRR-NET/duotang/assets/6340682/bf0bbd51-2e76-43ac-9aca-192cf2afec5a)

**Comment by bfjia** [comment]
![CaseCount_vs_Positive_Count](https://github.com/CoVaRR-NET/duotang/assets/6340682/14740288-d0bf-49e0-9f7c-5d9f7163e3dd)
![CaseCount_vs_Positive_Rate](https://github.com/CoVaRR-NET/duotang/assets/6340682/d8c35890-0b8f-43f8-80ac-50d38a8d2c91)
![CaseCount_vs_Gender_Cases_Count](https://github.com/CoVaRR-NET/duotang/assets/6340682/0984b6e3-74e0-44a0-bf1c-6a6e5c257830)
![CaseCount_vs_Outbreaks_Count](https://github.com/CoVaRR-NET/duotang/assets/6340682/e17e2f34-0774-4a85-9cee-87700583d744)

**Comment by bfjia** [comment]
Doesnt look like the negative correlation with positivity is due to a change in methodology. Recent samples were all non correlative. 
![CaseCount_vs_Positive_Rate](https://github.com/CoVaRR-NET/duotang/assets/6340682/a787d10f-f5aa-454a-b804-48b4b4933c47)
![CaseCount_vs_Positive_Count](https://github.com/CoVaRR-NET/duotang/assets/6340682/060d77d0-b158-4d12-81b2-6793ebd51465)

**Comment by bfjia** [comment]
Gender data is still updated weekly. Outbreak data is updated monthly. Positivity data updated weekly.

**Comment by bfjia** [comment]
As of July 3rd, the Outbreaks CSV seems to have changed. Overall, it seems lower compared to before for the last year

This is the correlation for the new outbreak CSV

![image](https://github.com/CoVaRR-NET/duotang/assets/6340682/458559c1-5ecd-459a-8bfa-9dd4181a4caa)

**Comment by bfjia** [comment]
Link to the outbreak CSV: https://health-infobase.canada.ca/src/data/covidLive/covid19-epiSummary-outbreaks-settings.csv
Link to the positivity CSV: https://health-infobase.canada.ca/src/data/covidLive/covid19-epiSummary-labIndicators2.csv

**Comment by bfjia** [comment]
Outbreak CSV from June 18th, 2024: https://1drv.ms/u/s!Ahefjh1UXa259qBCV1eFiccSC9yVPQ?e=clJBjd
Outbreak CSV from July 3rd, 2024. https://1drv.ms/u/s!Ahefjh1UXa259qBJUndDLnDhB9EJ1A?e=qn8k6v

**Comment by spotto** [comment]
I think the positivity data are OK.  I took a look at the test positivity times test number and it correlates well with case numbers (see attached excel file).  I don't get negative correlations, so maybe there was a bug? 
<img width="362" alt="image" src="https://github.com/CoVaRR-NET/duotang/assets/6675053/a63fdab2-4b90-4ae5-984a-768e19f5521c">
[CaseCountComparison.xlsx](https://github.com/user-attachments/files/16088645/CaseCountComparison.xlsx)

**Comment by spotto** [comment]
Positivity correlates less well (but still positive):  
<img width="362" alt="image" src="https://github.com/CoVaRR-NET/duotang/assets/6675053/615fb7bd-24b7-48ca-ba17-d015327645e7">

[Above use the case counts in covid19-epiSummary-weeklyEpiCur from https://health-infobase.canada.ca/covid-19/current-situation.html ]

**Comment by spotto** [comment]
Link to the positivity CSV is also still present at the bottom of https://health-infobase.canada.ca/covid-19/ (search for lab indicators)

**Comment by bfjia** [comment]
> Doesnt look like the negative correlation with positivity is due to a change in methodology. Recent data (since 2024-01-01) were all non correlative. ![CaseCount_vs_Positive_Rate](https://private-user-images.githubusercontent.com/6340682/345157931-a787d10f-f5aa-454a-b804-48b4b4933c47.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMjk0NjUsIm5iZiI6MTcyMDAyOTE2NSwicGF0aCI6Ii82MzQwNjgyLzM0NTE1NzkzMS1hNzg3ZDEwZi1mNWFhLTQ1NGEtYjgwNC00OGI0YjQ5MzNjNDcuSlBHP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDNUMTc1MjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjIwMGZkMjk2MDQ3MmNiNTA2ZjYxNGMxNWUyYzA1ODJhNThhYjgyMDFkZDQyNTc0ZDFlNWYwZTM3MDUwMTRlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.g-Jqzm1MQABi3JWb1JVaZfTlX467mdPfVlOYhFXEKGA) ![CaseCount_vs_Positive_Count](https://private-user-images.githubusercontent.com/6340682/345157969-060d77d0-b158-4d12-81b2-6793ebd51465.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMjk0NjUsIm5iZiI6MTcyMDAyOTE2NSwicGF0aCI6Ii82MzQwNjgyLzM0NTE1Nzk2OS0wNjBkNzdkMC1iMTU4LTRkMTItODFiMi02NzkzZWJkNTE0NjUuSlBHP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDNUMTc1MjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTRiODQ5OTk3MjgxMTk0MWMxMzM5NmRmZDdhZjVhNDJlYjQ3ZjUwZjE1NTliZmI3NzEwMWU0NzE1NTFjY2YzNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.j_8KRa0vx0T3DKmbIVYGIJ_4ifYOG63IogcFXKLv6Ds)

The different here is actually due to the fact that i used a wrong dataset. The [Respiratory Virus Detections dashboard](https://health-infobase.canada.ca/respiratory-virus-detections/) didn't actually exist until this week's update. Previously it was reported here via HTML tables. [https://web.archive.org/web/20240603032930/https://www.canada.ca/en/public-health/se[…]us-detections-canada/2023-2024/week-18-ending-may-4-2024.html](https://web.archive.org/web/20240603032930/https://www.canada.ca/en/public-health/se[%E2%80%A6]us-detections-canada/2023-2024/week-18-ending-may-4-2024.html)
I been using the Positive human coronavirus (HCoV) tests data which is incorrect and not actually COVID related.

**Comment by spotto** [comment]
Aha!  Glad that is sorted.  I think we can go with detections moving forward.  Interestingly, this page makes it sound like the data reported to PHAC is # of tests and # of detections, from which positivity is calculated (so we're just backtracking to get number of detections): https://health-infobase.canada.ca/respiratory-virus-detections/understanding.html
