### ISSUE TITLE
Make trees more user friendly

### ISSUE THREAD

**Issue by ArtPoon** [CoVaRR-NET/duotang#37]
interactive SVG, so that users can mouseover tip nodes to retrieve sample information
and an interactive JS tree would also enable users to switch between time and divergence scaling

**Comment by ArtPoon** [comment]
Tree should be drawn within a viewport of fixed height, so that it does not take up so much of the notebook's vertical extent.  User can use vertical scroll to examine different parts of the tree.

**Comment by ArtPoon** [comment]
In progress in `r2d3` branch

**Comment by bfjia** [comment]
Work in progress in fork. Ideally get it in before Dec 6th.
