### ISSUE TITLE
Adding n for reference in selection for recent variants

### ISSUE THREAD

**Issue by bfjia** [CoVaRR-NET/duotang#372]
One thing I would suggest is adding n=number for the reference too in the selection for recent variants, so the numbers for each curve are shown (currently only provided in the figure for the non-reference)

[Slack Message](https://covarr-net.slack.com/archives/C025AGXG7JT/p1721486590482139?thread_ts=1721480524.147469&cid=C025AGXG7JT)

**Comment by fionabrinkman** [comment]
Sounds good! I defer to Sally if there is any issue we’re not thinking of.
