### ISSUE TITLE
changing selection plot groupings

### ISSUE THREAD

**Issue by bfjia** [CoVaRR-NET/duotang#373]
Should we update our groupings?  Maybe JN.1*, KP.3*, KP*, and other? Could wait a week though.

[Slack Message](https://covarr-net.slack.com/archives/C025AGXG7JT/p1721486447441719?thread_ts=1721480524.147469&cid=C025AGXG7JT)

**Comment by fionabrinkman** [comment]
I’d be OK with this if you want to go for it
