### ISSUE TITLE
update "raphgraph"

### ISSUE THREAD

**Issue by ArtPoon** [CoVaRR-NET/duotang#38]
The plotting functionality of this Python script can be ported into R, which would make it easier to maintain.  It would also be helpful to make this plot interactive, e.g., zoom on specific mutations, genome regions.

**Comment by ArtPoon** [comment]
In progress, new branch `raphgraph`

**Comment by bfjia** [comment]
Could be more beneficial to keep separate if we move the a workflow management system.

**Comment by bfjia** [comment]
Closed, currently this is being halted by the alignment issue in issue #79.
