### ISSUE TITLE
Automate backend

### ISSUE THREAD

**Issue by ArtPoon** [CoVaRR-NET/duotang#42]
* in Slack poll, nextflow was selected as a framework to use for workflow management
* installed on mac with `brew install nextflow`
* apparently not available for Ubuntu with `apt` package manager

**Comment by ArtPoon** [comment]
My Ubuntu workstation is running Java version 8:
```console
art@orolo:~$ java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~18.04-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
art@orolo:~$ curl -s https://get.nextflow.io | bash
NOTE: Nextflow is not tested with Java 1.8.0_312 -- It's recommended the use of version 11 up to 18
```
This might cause problems later.

**Comment by bfjia** [comment]
Update 2023-02-21. Duotang can be automated with an AIO update script with a cron monitor. It is setup on Paphlagon, but in testing.

**Comment by bfjia** [comment]
See Issue 151
