### ISSUE TITLE
download.sh - detect `gtar` if macOS, add timestamp

### ISSUE THREAD

**Issue by ArtPoon** [CoVaRR-NET/duotang#43]
* macOS `tar` does not have the same functionality of GNU tar, so I've had to install the latter seprately using Homebrew, which provides `gtar`.  Our bash script needs to detect if it is being run on a macOS platform and then call `gtar` instead of `tar`.
* the tarball provided by VirusSeq contains a date and time stamp that needs to be extracted and applied to our output filenames, *i.e.*, instead of writing `virusseq.fasta.xz` we should be writing `virusseq.2022-04-11T20_03_59.fasta.xz`

**Comment by ArtPoon** [comment]
Ran into following error running on Ubuntu 18.04:
```
tar: Pattern matching characters used in file names
tar: Use --wildcards to enable pattern matching, or --no-wildcards to suppress this warning
tar: files-archive-592f95e0-6a4f-4ad6-bbe9-ab19da5cc663.tsv[0]: Not found in archive
tar: Exiting with failure status due to previous errors
```

**Comment by RaphaelRaphael** [comment]
Here is the bash cmd lines but I can t get the form $filenames[0] to make what it is supposed to make on my bash

```
#get the good tar command depending of bash or macos
tarcmd=$(case "$(uname -s)" in Darwin)  echo 'gtar';;  Linux) echo 'tar';; esac)
#get the timestamp for file name
datestamp=$(date --utc +%Y-%m-%dT%H_%M_%S)
# scan tarball for filenames
filenames=$($tarcmd -ztf virusseq.tar.gz)
# stream FASTA data into xz-compressed file
$tarcmd -axf virusseq.tar.gz -O $filenames[0] | xz > virusseq.$datestamp.fasta.xz
# stream metadata into gz-compressed file
$tarcmd -axf virusseq.tar.gz -O $filenames[1] | gzip > virusseq.$datestamp.metadata.tsv.gz
# delete tarball
rm virusseq.tar.gz
```

**Comment by RaphaelRaphael** [comment]
I think the script is ok now, I did made the change on a branch and pull the branch in dev, could you test it on mac OS ?

**Comment by RaphaelRaphael** [comment]
If anybody can test this on a mac we could close the issue I guess

**Comment by ArtPoon** [comment]
```console
art@Wernstrom data_needed % bash download.sh 
download.sh: line 2: syntax error near unexpected token `;;'
download.sh: line 2: `tarcmd=$(case "$(uname -s)" in Darwin)  echo 'gtar';;  Linux) echo 'tar';; esac)'
```

**Comment by RaphaelRaphael** [comment]
I did change the **case** statement by an **if** statement  and I don t find back this version on **download.sh**

**Comment by bfjia** [comment]
Resolved
