### ISSUE TITLE
Variant in canada overtime graph 

### ISSUE THREAD

**Issue by ArtPoon** [CoVaRR-NET/duotang#65]
`yoffset` is being initialized at several thousand pixels for some reason

**Comment by ArtPoon** [comment]
I simplified the code calculating the position of the SVG element to adjust mouse coordinates:
```js
    bodyRect = document.body.getBoundingClientRect(),
    elemRect = bpsvg.node().getBoundingClientRect(),
    yoffset = elemRect.top - bodyRect.top;
```
based on [this](https://stackoverflow.com/questions/25630035/javascript-getboundingclientrect-changes-while-scrolling) thread.

Since the `yoffset` was still a huge value (around `3000` pixels), I tried moving the following code into the SVG event handler for `mousemove`:
```js
      elemRect = bpsvg.node().getBoundingClientRect(),
      yoffset = elemRect.top - bodyRect.top;
```

**Comment by bfjia** [comment]
^Streamgraph tooltip is broken issue.
Issue changed to a overall discussion on the variant over time graph

**Comment by bfjia** [comment]
@ArtPoon Some inputs from you is needed for the silhouette plots. Specifically what does the Y-axis represent.

**Comment by ArtPoon** [comment]
The y-axis in a silhouette plot only serves the purpose of providing a "ruler" for the user to judge the number of sequences represented by a given shape, based on its height:
<img width="764" alt="Screen Shot 2022-12-05 at 10 15 23 PM" src="https://user-images.githubusercontent.com/1109328/205804188-1a85ae0e-03a3-4ff2-8a81-87c13841f2af.png">

In other words, the *absolute* position of a shape with respect to the ruler does not mean anything -- it is only the *relative* position of a shape's top and bottom that matter.

The only alternative to drawing a y-axis as a ruler is to draw a scale bar instead.  I've previously done this manually for static streamgraphs.
