### ISSUE TITLE
Automating VirusSeq release date that was run on DNA stack:

### ISSUE THREAD

**Issue by RaphaelRaphael** [CoVaRR-NET/duotang#66]
Just a note about this issue that seems to be minor

We could use the following command to extract the VirusSeq release date that was run on DNA stack: 

`    dnastack collections list | jq -r '.[] | select(.slugName=="virusseq") | .description' | sed -e 's:</p>:\n:g' -e 's:<br>:\n:g' | grep 'Release:' | grep -oE '[A-Z][a-z]+ [0-9]{1,2}, [0-9]{4} [0-9]{2}:[0-9]{2} (a.m.|p.m.)'
`
     Note in addition to our dnastack CLI this command requires having [jq](https://stedolan.github.io/jq/) installed.

**Comment by bfjia** [comment]
Extension of Issue #42

**Comment by RaphaelRaphael** [comment]
I just test and correct the command line and this one could be used in the download.sh script @anwarMZ 

`dnastack collections list | jq -r '.[] | select(.slugName=="virusseq") | .description' | sed -e 's:</p>:\n:g' -e 's:<br>:\n:g' | grep 'Release:' | grep -oE '[A-Z][a-z]+ [0-9]{1,2}, [0-9]{4} [0-9]{1,2}:[0-9]{2} (a.m.|p.m.)'`

**Comment by bfjia** [comment]
Anther alternative without requiring the `jq` program and uses build in python:
