### ISSUE TITLE
Highly divergent samples classified as "other"

### ISSUE THREAD

**Issue by ArtPoon** [CoVaRR-NET/duotang#69]
Whilst preparing last week's update, I noticed that some recent samples were classified as "other" (not a tracked VoC) but are clearly divergent from the baseline molecular clock, as illustrated by the following root-to-tip regression:
![image](https://user-images.githubusercontent.com/1109328/181404297-40694d5c-348c-41b9-a3e2-31d526950c41.png)

**Comment by ArtPoon** [comment]
@murallcl suggested that these may represent BE/BF/BA.2.75 samples that were not annotated as such

**Comment by ArtPoon** [comment]
Do we need to run a sequence QC prior to generating RTT plots?

**Comment by bfjia** [comment]
Resolved due to resolution of a pangolin issue
