### ISSUE TITLE
Add "Not enough data available" to Selection on Omicron plots

### ISSUE THREAD

**Issue by ArtPoon** [CoVaRR-NET/duotang#70]
For some provinces, we don't have enough data to fit competitive growth models, such as the "BA.2 sublineage selection" section.  Adding this footnote would help clarify why the plots are missing for the respective tabs:
<img width="858" alt="Screen Shot 2022-07-27 at 10 07 49 PM" src="https://user-images.githubusercontent.com/1109328/181404721-51fd1e24-ed63-43d3-af33-0af3b4a219ab.png">

**Comment by bfjia** [comment]
Resolved.
