### ISSUE TITLE
Key runs off 

### ISSUE THREAD

**Issue by spotto** [CoVaRR-NET/duotang#77]
In the section "Major Omicron sublineages in Canada", the key runs off the bottom if there are too many sub-lineages (e.g., for BA.2).  Maybe add a second column or restrict to only those that have ever been >0.1% of the variant?  Also, it would be nice to hover over the bar chart to see which colour is which, but this might not be so bad if we restricted to only those variants that are >0.1% and so didn't have a ton of variants.

**Comment by bfjia** [comment]
Resolved by adding other category in grey
