### ISSUE TITLE
Discordant outputs from minimap2 and GISAID alignments

### ISSUE THREAD

**Issue by ArtPoon** [CoVaRR-NET/duotang#79]
For generating the "raphgraph" plot, we are using a combination of Genbank data and VirusSeq data to extract the frequencies of mutations for specific variants of concern; see https://github.com/CoVaRR-NET/duotang/blob/main/scripts/get-mutations.py

The problem is that raphgraphs were originally generated from GISAID (MAFFT)-aligned genome sequences, and minimap2 can place nucleotides in a different position in rare cases of ambiguous alignments.  In the following example from @RaphaelRaphael, the first set of columns (left) is from `get-mutations.py` and the second is from MAFFT:
```tsv
POS    REF  A      C      G      T      .      POS    REF  A      C      G      T      Del    N
21633  T    0      0.02   0      0.06   99.9   21633  T    0      97.59  0      0.18   0.16   2.05
21634  A    0.03   0      0      0      99.96  21634  A    97.74  0      0      0      0.16   2.08
21642  C    0      97.51  0      0      2.48   21642  C    0      1.73   0      0      97.62  0.64
21643  A    97.55  0      0.01   0      2.43   21643  A    1.78   0      0      0      97.62  0.58
21765  T    0      0      0      0.3    99.69  21765  T    0      0      0      98.06  0.44   1.49
21766  A    0.19   0.04   0      0      99.76  21766  A    0.61   96.95  0      0.3    0.45   1.66
21771  T    0      0      0      97.58  2.41   21771  T    0      0      0      2.21   97.35  0.42
21772  C    0      97.53  0      0      2.46   21772  C    0      2.48   0      0      97.22  0.29
28362  G    0      0      0.21   0.01   99.77  28362  G    0      0      69.69  0.02   28.78  1.49
28363  A    0.13   0      0      0.06   99.8   28363  A    0.26   0      0.07   69.03  28.78  1.83
28371  G    0      0      71.04  17.09  11.86  28371  G    0      0      2.84   21.8   70.62  4.72
28372  T    0      0      0      97.25  2.74   28372  T    0      0      0      30.92  68.78  0.28
```

Taking the majority base in either case, we can generate the following:
```
>minimap2
--CA--TC--GT
>mafft
CA--TC--GA--
```

**Comment by RaphaelRaphael** [comment]
So here is a comparison of minimap2 ( from alignemnt.py - duotang) and mafft  from GISAID (details on demand)
[list_problematic_sites.tsv.zip](https://github.com/CoVaRR-NET/duotang/files/9675295/list_problematic_sites.tsv.zip)

**Comment by ArtPoon** [comment]
@RaphaelRaphael - thanks for uploading the TSV file.  The bulk of rows in that file appear to be associated with a very small number of genomes (<50).  It is not possible for us to verify these unless we have a more informative sample identifier - currently we only have sample number.

**Comment by RaphaelRaphael** [comment]
I just added the file with GISAID ids here : /home/rpoujol/id_ncov_GISAID_pos_missmatches.tsv in duotang's serve

**Comment by bfjia** [comment]
Extension of Issue #24

**Comment by ArtPoon** [comment]
Generating test files to reproduce the issue, based on first five genomes in `id_ncov_GISAID_pos_missmatches.tsv`:
```console
art@orolo:~/git/duotang/data_needed$ gunzip -c ncov-open.2022-05-12.tsv.gz | grep -E "EPI_ISL_1001477|EPI_ISL_1001480|EPI_ISL_1001492|EPI_ISL_1001499|EPI_ISL_1001501" > iss79.tsv
art@orolo:~/git/duotang/data_needed$ unxz -c ncov-open.2022-05-12.fasta.xz | grep -E -A1 "Switzerland/AG-ETHZ-451157/2021|Switzerland/LU-ETHZ-450497/2021|Switzerland/LU-ETHZ-450563/2021|Switzerland/SZ-ETHZ-470943/2021|Switzerland/ZH-ETHZ-480541/2021" > iss79.fasta
```
* Manually added metadata header
* manually reset all PANGO lineage assignments to `B.1`

**Comment by bfjia** [comment]
Closed as we removed RaphGraph in replacement of COVID-MVP
