### ISSUE TITLE
Error Handling and compartmentalize of RMD 

### ISSUE THREAD

**Issue by bfjia** [CoVaRR-NET/duotang#87]
To facilitate the automated building of the Duotang html, a part of this involves building in better error handling into sections of the rendering code. 

Here's a proposed solution: 
- We break down the current RMD file into different files. With each major section correspond to 1 separate rmd file and a main rmd file to render the sections together
- Each section will have it's independent error handling based on the most common issues within that section. This may include filtering for NAs, default empty plot in case of errors, etc...
- Breaking it down into separate files will also make reorganizing the section order much easier, and if in the future we move the Shiny, the different rmds could also be different pages on the shiny app. 
- There's a good amount of variables throughout the rmd that need to be manually changed with each update. Move these into a separate universal config file so unless there's a necessary code change (i.e. adding a new type of plots), we don't touch the rmd during an update. 

Welcome any additional inputs. Please also comment on what are some of the most common errors you run into while knitting the HTML file.

**Comment by bfjia** [comment]
We break down the current RMD file into different files. With each major section correspond to 1 separate rmd file and a main rmd file to render the sections together
^Not stictly necessary. Each part of the RMD should have it's own R module. then in the RMD you call that module.

**Comment by bfjia** [comment]
https://files.slack.com/files-pri/T021B8SKGLT-F04CBHJ649X/duotang.png

the different sections ^

**Comment by anwarMZ** [comment]
@anwarMZ modularizing [Major Omicron sublineages in Canada](https://covarr-net.github.io/duotang/duotang.html#Selection_on_Omicron)

**Comment by bfjia** [comment]
@bfjia Trees and selection plots

**Comment by RaphaelRaphael** [comment]
Error handling is now ok :)
