### ISSUE TITLE
interactive selection graphs + reference selection

### ISSUE THREAD

**Issue by ArtPoon** [CoVaRR-NET/duotang#88]
I think these plots would be a good candidate for interactivity - to have a summary plot to the left showing estimates for all sublineages, and a detail plot on the right where the user can switch between these scatterplots showing fit of logistic model

[Slack Message](https://covarr-net.slack.com/archives/C020WAJS0DD/p1666878460697049)

**Comment by ArtPoon** [comment]
From @RaphaelRaphael : We could also show all the selection estimates above 0 for any monophyletic "group of variants" that do not include reference; Or for non monophyletic usage : we could group lineages according to which mutations they have as here R346X L452X and F486X are all common to some lineages

**Comment by ArtPoon** [comment]
From @jesseshapiro : another opportunity for interactivity -- e.g. select which mutations to include (from a curated list?)

**Comment by RaphaelRaphael** [comment]
Should we try to generate interactivity over some pre-generated jpeg or to store all the data needed for each plot in the web page ?

**Comment by ArtPoon** [comment]
I would rather have the plots genearted client-side, but the challenge is how to transmit the required data in a compact way

**Comment by bfjia** [comment]
probably better to be the latter. could make use of d3 like the variant over time plot

**Comment by ArtPoon** [comment]
we wouldn't want to have to reimplement the selection model fitting in JS though

**Comment by ArtPoon** [comment]
probably the most efficient approach would be to store regression model parameters and plot coordinates of points for all lineages of interest - and regression model params for sets of lineages

**Comment by bfjia** [comment]
Make everything that has significantly higher than 0 growth default to view for interactive tree. This graph would show overlapping models/lines.

**Comment by bfjia** [comment]
Calculate selection coefficient for ALL sublineages, then have a dropdown for choosing sublineages.

**Comment by bfjia** [comment]
Are we happy with the reference right now? do we want to try different? Needs some additional information.

**Comment by ArtPoon** [comment]
@bfjia what's the status on this?  want help?

**Comment by bfjia** [comment]
Lets discuss this next Tuesday. I got the framework for this started but we need to discuss what the best way to visualize this will be.

**Comment by bfjia** [comment]
move the plots to below fastest growing lineage plot then show the top 3 with the rest hidden, if possible.
