### ISSUE TITLE
Version tracking

### ISSUE THREAD

**Issue by RaphaelRaphael** [CoVaRR-NET/duotang#92]
Find a way to navigate to all or some of the ancient versions of duotang. (Sally s request)

**Comment by bfjia** [comment]
Pull it from the commit history?

**Comment by bfjia** [comment]
https://stackoverflow.com/questions/39213406/get-files-from-each-git-commit
^this might work

**Comment by ArtPoon** [comment]
Certainly we can retrieve older versions of the HTML files from past commits, but the main problem is how to make these publicly accessible.  There is (as far as I know) no way to navigate to a previous commit via GitHub pages.

**Comment by ArtPoon** [comment]
Which would mean that we would have to host these HTML files on another server, which is not ideal.

**Comment by bfjia** [comment]
VirusSeq might be able to host this to avoid the 3rd party url redirects. @erin to ask at viruseq meeting

**Comment by eringill** [comment]
Data Portal is open to the idea of hosting older versions of duotang. They envision a page similar to "[Data Releases](https://virusseq-dataportal.ca/releases)", where there is a table with a list of dates, and then links to our HTML files. [Scott Cain](scott@scottcain.net) is the contact person. I've suggested he contact @ArtPoon for more info.

**Comment by ArtPoon** [comment]
@bfjia got this working at this URL, I think:
https://covarr-net.github.io/duotang/archive/
